djangoSite/urls.py
from django.conf.urls import url, include
from django.contrib import auth
from django.contrib import admin
from djangoSite import views
# from access.views import view_user_deal

urlpatterns = [
    url('^', include('django.contrib.auth.urls'), name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/', views.profile, name='profile'),
    url(r'^logged_out/$', views.logout_user, name='loggedout'),
    url(r'^$', views.index, name='homepage'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^chart/$', views.dealtrend, name='dealtrend'),
    url(r'^parser/$', views.addparser, name='parser'),
    url(r'^api/plottrend/$', views.plottrend, name='api_plottrend'),
    url(r'^api/getdeal/$', views.generate_deal_data, name='api_getdeal'),
    url(r'^api/getdealforthisparser/$', views.get_deal_for_parser, name='api_deal_for_parser'),
    # url(r'^user_deal/$', view_user_deal, name='view_user_deal'),
]

books/models.py
from django.db import models

# Create your models here.

class BookManager(models.Manager):
	"""docstring for BookManager"""
	def title_count(self, keyword):
		return self.filter(title__icontains=keyword).count()
		

class Publisher(models.Model):
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=30)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()

	class Meta:
		ordering = ["-name"]

	def __str__(self):
		return self.name


class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField(blank=True)

	def __str__(self):
		return u'%s %s' % (self.first_name, 
			self.last_name)


class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	publication_date = models.DateField(blank=True,
										null=True)
	num_pages = models.IntegerField(blank=True, null=True)
	objects = BookManager()
	

	def __str__(self):
		return self.title

parsers/models.py
from django.db import models

# Create your models here.
class Parser(models.Model):
	name = models.CharField(max_length=100, unique=True)
	filepath = models.CharField(max_length=500, blank=True)
	
	def __str__(self):
		return self.name


class Category(models.Model):
	brand = models.CharField(max_length=50)
	mainclass = models.CharField(max_length=50)
	subclass = models.CharField(max_length=50)

	def __str__(self):
		return "%s -> %s || <Brand> %s" % (self.mainclass, \
										self.subclass, \
										self.brand)


class Deal(models.Model):
	title = models.CharField(max_length=100)
	category = models.ForeignKey(Category)
	website = models.URLField()
	parser = models.ForeignKey(Parser)
	
	def __str__(self):
		return self.title

class Price(models.Model):
	deal = models.ForeignKey(Deal)
	price = models.CharField(max_length=100)
	date = models.DateTimeField()

	def __str__(self):
		return "{2} on {0}: ${1}".format(self.date, self.price, self.deal)

djangoSite/forms.py
from django import forms
from parsers.models import Category, Parser

# customized field
# credit to https://stackoverflow.com/questions/24783275/django-form-with-choices-but-also-with-freetext-option
class ListTextWidget(forms.TextInput):
    def __init__(self, selection, name, *args, **kwargs):
        super(ListTextWidget, self).__init__(*args, **kwargs)
        self._name = name
        self._list = selection
        self.attrs.update({'list':'list__%s' % self._name})

    def render(self, name, value, attrs=None):
        text_html = super(ListTextWidget, self).render(name, value, attrs=attrs)
        selection = '<datalist id="list__%s">' % self._name
        for item in self._list:
            selection += '<option value="%s">' % item
        selection += '</datalist>'

        return (text_html + selection)

# =============

class ContactForm(forms.Form):
    # TODO: Define form fields here
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, \
    		label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
    	message = self.cleaned_data['message']
    	num_words = len(message.split())
    	if num_words < 1:
    		raise forms.ValidationError("Not enough words! Minimal 1")
    	return message

class SelectDeal(forms.Form):
    def __init__(self, dealName):
        self.dealName = dealName
        super(SelectDeal, self).__init__()
        self.fields['dealMenu'] = forms.ChoiceField(zip(self.dealName,self.dealName))

class SelectCategory(forms.Form):
    def __init__(self, brand, mainclass, subclass, item = None):
        self.brand = brand
        self.mainclass = mainclass
        self.subclass = subclass
        self.item = item
        super(SelectCategory, self).__init__()
        self.fields['brand'] = forms.ChoiceField(zip(self.brand,self.brand))
        self.fields['mainclass'] = forms.ChoiceField(zip(self.mainclass,self.mainclass))
        self.fields['subclass'] = forms.ChoiceField(zip(self.subclass,self.subclass))
        if self.item:
            self.fields['item'] = forms.ChoiceField(zip(self.item,self.item))

    def AddItem(self, item):
        if item:
            self.fields['item'] = forms.ChoiceField(zip(item,item))

class AddParser(forms.Form):
    name = forms.CharField(max_length=100,min_length=1)
    body = forms.CharField(widget=forms.Textarea(attrs={'cols': 30, 'rows': 10}))
    filename = forms.CharField(max_length=100,min_length=1)

class AddDeal(forms.Form):
    title = forms.CharField(max_length=100,min_length=1)
    website = forms.URLField()
    # filename = forms.CharField(max_length=100,min_length=1)
    
    def addparser(self, queryset, id):
        self.fields['parser'] = forms.ModelChoiceField(widget=forms.Select(attrs={'id': id}), \
                                                               queryset= queryset)

class AddCategory(forms.Form):
    brand = forms.CharField(max_length=50,min_length=1)
    mainclass = forms.CharField(max_length=50,min_length=1)
    subclass = forms.CharField(max_length=50,min_length=1)
    def __init__(self, brand, mainclass, subclass):
        super(AddCategory, self).__init__()
        self.fields['brand'].widget = ListTextWidget(selection=brand, \
                                                    name='band-list')
        self.fields['mainclass'].widget = ListTextWidget(selection=mainclass, \
                                                         name='mainclass-list')
        self.fields['subclass'].widget = ListTextWidget(selection=subclass, \
                                                        name='subclass-list')

class SelectParser(forms.Form):
    def __init__(self, choices = None):
        self.choices = choices
        super(SelectParser, self).__init__()
        if self.choices:
            choices = list(zip(self.choices,self.choices))
            self.fields['parser'] = forms.ChoiceField(widget=forms.Select(attrs={'id': 'form_select_parser'}),\
                                                      choices=choices, \
                                                      initial=choices[0])

    def AddItem(self, item):
        if item:
            self.fields['parser'] = forms.ChoiceField(widget=forms.Select(attrs={'id': 'form_select_parser'}),\
                                                      choices=zip(item,item))

class QueryMenu(forms.Form):
    '''Create select menu containing accessible deals for user'''
    modelquerymenu = None
    def __init__(self, queryset, id):
        super(QueryMenu, self).__init__()
        self.fields['modelquerymenu'] = forms.ModelChoiceField(widget=forms.Select(attrs={'id': id}), \
                                                               queryset= queryset)

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">

<html lang="en">
{% load static %}
<head>
    <script type="text/javascript" src="{% static 'js/functions.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div id="page-wrapper">
    <h1>PROJECT DEAL SNIFFER</h1>
    <div class="navi">
    <a href="{% url 'homepage' %}">Home</a> | 
    <a href="{% url 'contact' %}">Contact Us</a> | 
    {% if request.user.is_authenticated %}
    <a href="{% url 'dealtrend' %}">Deal Trend</a> |
        {% if request.user.is_staff %}
        <a href="{% url 'parser' %}">Parsers</a> |
        {% endif %}
    <a href="{% url 'loggedout' %}">Logout</a> |
    <a href="{% url 'profile' %}">Profile</a> |
    {% else %}
    <a href="{% url 'login' %}?next={% url 'homepage' %}">Login</a> |
    {% endif %} 
    <a href="https://github.com/staftermath/dealsniffer" target="_blank">GitHub</a>
    </div>
    <hr>
    {% block content %}{% endblock %}
    {% block chart %}{% endblock %}

    <div id="footer">
    {% block footer %}
    <hr style="width: 100%; height: 100%; float: bottom;">
    <div style="width: 100%; height: 100%; float: bottom;">Thanks for visiting my site. <a href="{% url 'contact' %}">Contact Us</a></div>
    {% endblock %}
    </div>
</div>
</body>
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}?v=<?=time();?>" />
<link rel="stylesheet" type="text/css" href="{% static 'css/tab.css' %}?v=<?=time();?>" />

</html>

templates/chart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Deal Trend{% endblock %}
{% block content %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript">
var parsedMenu = JSON.parse("{{menuDict}}".replace(/&quot;/g,'"'));
var MENULIST = ['brand', 'mainclass', 'subclass', 'title'];
{% if selected %}
	var selected = JSON.parse("{{selected}}".replace(/&quot;/g,'"'));
{% else %}
	var selected = null;
{% endif %}
function UpdateOneMenu(menu, menuList=MENULIST, object=parsedMenu, id_prefix="menu_") {
	// get List
	index = menuList.indexOf(menu)
	// find the menu
	for (i = 0; i < index; i++) {
		selectedValue = document.getElementById(id_prefix+menuList[i]).value
	// console.log("Selected Value for Menu "+ menuList[i] +" is " + selectedValue)
		object = object[selectedValue]
	};
	// Update all select menu after this level
	for (k = index; k < menuList.length; k++) {
		thisMenu = menuList[k]
	// get menu list. Array if it's the inner-most object. Otherwise Object and need to get keys
		if (object.constructor === Object) {
			newMenuList = Object.keys(object)
		} else if (object.constructor === Array) {
			newMenuList = object
		}
	// Append menulist
		tag = $("#"+id_prefix+thisMenu);
		tag.html('')
		if (newMenuList.length > 0){
			for (j = 0; j < newMenuList.length; j++) {
				tag.append($('<option>', {value:newMenuList[j], text:newMenuList[j]}));	
			};
			tag.val(newMenuList[0]);
		}
		object = object[newMenuList[0]]
	};
};
var selectMenuTemplate = '<select id="%ID%" name="%NAME%" style="width: 100px"></select>'
function UpdateAllMenu(menuList, object, formId, template, selected = selected){
	// console.log("selected passed to UpdateAllMenu function:")
	// console.log(selected)
	for (var i=0; i < menuList.length; i++){
		menu = menuList[i]
		selectTemplate = template.replace("%ID%", "menu_"+menu).replace("%NAME%", menu);
		$("#"+formId ).append($.parseHTML(selectTemplate))
		$("#"+formId ).append('|')
		if (object.constructor === Object) {
			newMenuList = Object.keys(object)
			object = object[newMenuList[0]]
		} else if (object.constructor === Array) {
			newMenuList = object
		}
		tag = $("#"+"menu_"+menu)
		// console.log("Updating Menu:")
		// console.log(newMenuList)
		for (j = 0; j < newMenuList.length; j++) {
			tag.append($('<option>', {value:newMenuList[j], text:newMenuList[j]}));	
		};
		if (selected == null) {
			tag.val(newMenuList[0]).change();
		} else {
			// console.log("Changing "+selected[menu])
			tag.val(selected[menu]).change();
		}
	};
	// default selection
	// add on change
	onchangeTemplate = "UpdateOneMenu(menu='%MENU%')"
	for (var i=0; i < menuList.length-1; i++){
		tag = $("#"+"menu_"+menuList[i])
		tag.attr("onchange", onchangeTemplate.replace("%MENU%", menuList[i+1]))
	}
	
	$("#"+formId ).append($.parseHTML('<button type="button" onclick="LoadChart()">Submit</button>'))
};

function LoadChart(menuList = MENULIST){
	var returnMenuValue = {}
	for (var i = 0; i < menuList.length; i++){
		menu = menuList[i]
		// console.log(menu)
		// console.log($("#menu_"+menu).val())
		returnMenuValue[menu] = $("#menu_"+menu).val()
	}
	var url = "{% url 'api_plottrend' %}?"+jQuery.param(returnMenuValue)
	var template = '<object type="text/html" data="%URL%" style="height:100%; width:100%;"></object>';
	// console.log("Load URL:")
	// console.log(url)
	document.getElementById("chartContainer").innerHTML = template.replace("%URL%", url)
};
</script>
<form id="menu_form" method="get">
</form>
<script type="text/javascript">
	UpdateAllMenu(menulist=MENULIST,
				  object=parsedMenu,
				  formId="menu_form",
				  template=selectMenuTemplate,
				  selected=selected
				  )
</script>

{% endblock %}
{% block chart %}
<div id="chartContainer" style="height:600px">
</div>
{% endblock %}

templates/chart_backup.html
{% extends 'base.html' %}
{% block title %}Deal Trend{% endblock %}
{% block content %}
<form method="get|post">
<table>
{% for form in categorySelect %}
{{ form }} |
{% endfor %}
<input type="submit" name="submit">
</table>
</form>
{% endblock %}
{% block chart %}
{% load static %}
<div id="chartContainer">
	<script src="{% static 'js/d3.v4.min.js' %}"></script>
	<script src="{% static 'js/dimple.v2.3.0.min.js' %}"></script>
	<script type="text/javascript">
    var svg = dimple.newSvg("#chartContainer", 700, 500);
    var parseDate = d3.utcParse("%Y-%m-%dT%H:%M:%S%Z");
    var axixDate = d3.timeFormat("%H:%M:%S %m/%d")
    var parseddata = JSON.parse("{{data}}".replace(/&quot;/g,'"'))

    for (var i = 0, len = parseddata.length; i < len; i++) {
    	parseddata[i].date = axixDate(parseDate(parseddata[i].date))
		parseddata[i].price = parseFloat(parseddata[i].price)
	}
      
	var myChart = new dimple.chart(svg, parseddata);
	myChart.setBounds(60, 30, 600, 300);
	var x = myChart.addCategoryAxis("x", "date");
	x.addOrderRule("Date");
	var y = myChart.addMeasureAxis("y", "price");
	var s = myChart.addSeries(null, dimple.plot.line);
	myChart.draw();

  </script>
</div>
{% endblock %}

templates/contact_form.html
{% extends "base.html" %}
{% block title %}
Contact Us
{% endblock %}
{% block content %}
	<h1>Contact us</h1>

	{% if form.errors %}
		<p style="color: red;">
		Please correct the error{{ form.errors|pluralize }} below.</p>
	{% endif %}
	<form action="" method="post">
	<table>
		<tr>
		<div class="field">
			{{ form.subejct.errors }}		
			<td><label for="id_subject">Subject:</label></td>
			<td>{{ form.subject}}</td>
		</div>
		</tr>
		<tr>
		<div class="field">
			{{ form.email.erros }}
			<td><label for="id_email">Your e-mail address:</label></td>
			<td>{{ form.email }}</td>
		</div>
		</tr>
		<tr>
		<div class="field">
			{{ form.message.errors}}
			<td><label for="id_message">Message:</label></td>
			<td>{{ form.message }}</td>
		</div>
		</tr>
		{% csrf_token %}
		<tr>
		<td><input type="submit" name="Submit" class="submit_button"></td>
		</tr>
	</table>
	</form>
{% endblock %}

templates/current_datetime.html
{% extends "base.html" %}
{% block title %}The current time{% endblock %}
{% block content %} 
	<p>It is now {{ current_date }}.</p>
{% endblock %}

templates/display_deal.html
{% load static %}
<div class="columns" style="width:100%;">
  <ul class="price">
    <li class="header {% if dealresult.inStock == 'In Stock' %}instock{% endif %}">{{dealresult.inStock}}</li>
    <li class="price_value">{{dealresult.Price}}</li>
    {% if dealresult.dealurl %}
	<li><button type="button" name="goto_deal" value="Go To Deal"
        onclick="window.open('{{ dealresult.dealurl }}');" class="submit_button">Go Now</button></li>
{% endif %}
  </ul>
</div>
<link rel="stylesheet" type="text/css" href="{% static 'css/price_table.css' %}?v=<?=time();?>" />

templates/hours_ahead.html
{% extends "base.html" %}
{% block title %}Future time{% endblock %}
{% block content %}
	<p>
		In {{ hour_offset }} hour(s), it will be {{ next_time }}.
	</p>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}
<h2>{% if request.user.is_authenticated %}
Hi, {{ request.user.username }}!
{% endif %} Welcome to the Home Page</h2>
<hr>
{% if request.user.is_authenticated %}
<table>
	{% for form in menuUserDealAccessible %}
	<tr>
		<td>Select Deal</td>
		<td>{{ form }}</td>
		<td><button type="button" name="get_deal" value="Get Deal"
            onclick="GetDeal(deal=$('#menu_user_deal_accessible').val(), targetid='display_deal', url='{% url 'api_getdeal'%}')" class="submit_button">Get Deal</button></td>
	</tr>
	{% endfor %}
	{% csrf_token %}
	<tr>
		<td></td>
		<td id="display_deal"></td>
		<td></td>
	</tr>
</table>
{% endif %}
{% load static %}

{% endblock %}

templates/log_out.html
{% extends "base.html" %}
{% block title %}Log Out Successful{% endblock %}
{% block content %}
<h2>You have been logged out.</h2>
{% endblock %}

templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
{% if error %}
	<p style="color: red;">Please submit a search term.</p>
{% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

templates/user_profile.html
{% extends "base.html" %}
{% block title %}
User Profile
{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
<table>
<tr>
	<td>Username:</td>
	<td>{{ request.user.username }}</td>
</tr>
<tr>
	<td>E-mail:</td>
	<td>{{ request.user.email }}</td>
</tr>
<tr>
	<td>First Name:</td>
	<td>{{ request.user.first_name }}</td>
</tr>
<tr>
	<td>Last Name:</td>
	<td>{{ request.user.last_name }}</td>
</tr>
	{% for form in menuUserDealAccessible %}
	<tr>
		<td>{{ form.name}}</td>
		<td>{{ form }}</td>
	</tr>
	{% endfor %}
</table>
{% else %}
<h1>You need to log in to view your profile</h1>
{% endif %}
{% endblock %}

templates/view_deal.html
<tr>
	   	<td>
        <select id="deal_menu" name="deal_menu" style="width:80%">
        </select>
        </td>
    	<td style="width:20%"><button type="button" name="get_deal" value="Get Deal"
            onclick="GetDeal(deal=$('#deal_menu').val(), targetid='display_deal', url='{% url 'api_getdeal'%}')" class="submit_button">Get Deal</button></td>
</tr>

templates/view_parser.html
{% extends 'base.html' %}
{% block title%}Add and View Parsers{% endblock %}
{% block content %}
{% load static %}
{# <link rel="stylesheet" type="text/css" href="{% static 'css/tab.css' %}"+ /> #}
{# <link rel="stylesheet" type="text/css" href="{% static 'css/deal_table.css' %}" /> #}
<script type="text/javascript">
	
	function hideAllTabs(tabclass){
		$('.'+tabclass).each(function(index, item){$(item).attr('style','display:none')});
	}

	function showTab(id, tabclass){
		hideAllTabs(tabclass=tabclass);
		var myElement = document.getElementById(id);
		myElement.style.display = 'inherit';
	}

</script>
<div id="LeftPanel" style="width: 50%; height: 100%; float: left;" class="Panel">
	<div class="tab">
	  <button class="tablinks" onclick="showTab('tab_parser','tabcontent_left')">Add Parser</button>
	  <button class="tablinks" onclick="showTab('tab_deal','tabcontent_left')">Add Deal</button>
	</div>

	<div id="tab_parser" class="tabcontent_left div_menu">
		<form method="post">
		<table id="table_addparser">
		<tr><td colspan="2" align="center" class="class_tablehead">Add Parsers</td></tr>
		{% for form in addparser %}
			<tr>
			<td align="right">{{form.name}}</td>
			<td>{{form}}</td>
			</tr>
		{% endfor %}
		{% csrf_token %} 
		<tr><td></td><td><button type="submit" name="add_parser" value="add_parser" class="submit_button">Submit</button></td></tr>
		</table>
		{% csrf_token %} 
		</form>
		{% for msg in msgs %}
		<div><span class="{% if validparser %}class_warning{% else %}class_fatal{% endif %}"><strong>{{msg}}</strong></span></div>
		{% endfor %}
	</div>
	<div id="tab_deal" class="tabcontent_left div_menu" style="display:none">
		<form method="post">
		<table id="table_adddeal">
		<tr><td colspan="2" align="center" class="class_tablehead">Add Deal</td></tr>
		{% for form in adddeal %}
			<tr>
			<td>{{form.name}}</td>
			<td>{{form}}</td>
			</tr>
		{% endfor %}
		{% for form in categoryform %}
			<tr>
			<td>{{form.name}}</td>
			<td>{{form}}</td>
		{% endfor %}
		{% csrf_token %}
		<tr><td></td><td><button type="submit" name="add_deal" value="add_deal" class="submit_button">Submit</button></td></tr>
		</table>
		</form>
	{% csrf_token %} 
	</div>


</div>
{% load static %}
<script type="text/javascript">
function GetDealForThisParser(elem) {
	// console.log("Getting parser: "+elem.options[elem.selectedIndex].value)
	var url = "{% url 'api_deal_for_parser' %}" + "?parser=" + elem.options[elem.selectedIndex].value
	console.log(url)
	var deals = jQuery.when(jQuery.getJSON(url)).done(
		function(json) {
			$("#deal_menu").html("");
			for (var i = 0; i< json.length; i++)
			{
				$("#deal_menu").append($('<option/>', { 
			        value: json[i][0],
			        text : json[i][1]
				    }));
					if (i==0) {
						$("#deal_menu").children().last().attr("selected","selected");
					}
			}
						});

};

</script>
<div id="RightPanel" style="width: 50%; height: 100%; float: right;" class="Panel">
<div class="tab">
	  <button class="tablinks">View</button>
</div>
<div class="tabcontent_right div_menu">
<table>
<tr>
	<td style="width:50%">{{ parsermenu.modelquerymenu }}</td>
	<td style="width:20%"><button type="button" id="view_parser" onclick="GetDealForThisParser(elem=document.getElementById('form_select_parser_view_deal'))" class="submit_button">View Deal</button></td> 
	<td style="width:20%">
		{% if request.user.is_superuser %}
			<button type="button" id="del_parser" onclick="" class="submit_button">Delete</button>
		{% endif %}
	</td>
</tr>
<tr>
   	<td>
    <select id="deal_menu" name="deal_menu" style="width:100%">
    </select>
    </td>
	<td style="width:20%"><button type="button" name="get_deal" value="Get Deal"
        onclick="GetDeal(deal=$('#deal_menu').val(), targetid='display_deal', url='{% url 'api_getdeal'%}')" class="submit_button">Get Deal</button></td>
    <td></td>
</tr>
<tr>
	<td id="display_deal"></td>
	<td></td>
	<td></td>
</tr>
</table>
</div>
<script type="text/javascript">
ChangeSelected('#id_parser')
</script>
{% endblock %}

templates/view_user_deal.html
<table>
	{% for form in menuUserDealAccessible %}
	<tr>
		<td>{{ form.name}}</td>
		<td>{{ form }}</td>
	</tr>
	{% endfor %}

<tr>
   	<td>
    </td>
	<td style="width:20%"><button type="button" name="get_deal" value="Get Deal"
        onclick="GetDeal(deal=$('#menu_user_deal_accessible').val(), parser=$('#form_select_parser').val())" class="submit_button">Get Deal</button></td>
</tr>
</table>
<script type="text/javascript">
{% load static %}
function GetDeal(deal, parser) {
    // $(this).after("<img src='{% static 'image/pageLoad.gif' %}' alt='loading' />").fadeIn(); 
    var url = "{% url 'api_getdeal'%}" + "?deal="+deal + "&parser=" + parser;
    console.log(url)
    var template = '<object type="text/html" data="%URL%" style="height:100%; width:100%;"></object>';
    document.getElementById("display_deal").innerHTML = template.replace("%URL%", url)
}
</script>